# Generated by Django 4.2.3 on 2023-07-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dynamic", "0003_modelpopulator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelpopulator",
            name="fields",
            field=models.JSONField(),
        ),
    ]
